sudo: required
script:
- bash test.sh
deploy:
  provider: releases
  api_key:
    secure: 2Q66cKH59vht0c7AriqF9sYvPDgeJPW0iihYSK4ThEZNgOs4mLoaUZHWNzMSwN4M3CNoahLJDyQG4MbgH1b7jMPcY2Zj8PMBGz3HEU2DOZTbI7Ex/S+rmpKm1zvNokrDEhbHXFi88Mo7T/W+Cf09Z2C2Pf1IizjBgZw5NIVxsiU9m1OvMYjeQfti7io1IRFpVsDgQ+AR0wqdCkQuNn7ZDavdslsDc2KsxNMnvxw19h4aG9Ia66Ax6fuGiEPfeyMXUiSabwWPQST8GlgjH0EmNJxnaKEC7SslvOhSoERhfvZ1riXP96ezjo8Zjs/IOcH2tERqwYOabx7JFfh4TAynEuytG1IYsO8xzgafqO6wSBq2UoKWrmV3/+edbs9gbq/8BuYgrJ5fytusDfFZZ+4fGZyzEVUkDZm83bXSO0t2yqmCjKqJ6ptI1+zB5fiChZDHfSk8AzY4GiARtcy55xLoabFfmwT4ia0RXcLEsOFNm4DqRjgo9z6tFXphCUolyuaFzMT30dzqmOgndgSLl3f0Iv507c4PJ5txamTq+Amlu/3oQZPkhiVRHCod4iIkSs5IqaLgqtbY3y+BSfhm9hnBrftx7LB5siLGmed0Q0kTtgaVvWYr28NLe0wvJtxEXDmK6IX6fcmYOpYPxToaGFSaspcYvuKE+BcGZ3dUizZasII=
  file: hello.sh
  skip_cleanup: true
  on:
    tags: true
    repo: firedot/travis_cd
